# Sonar thresholds
FRONT_CAUTION_CM = 40.0
FRONT_DANGER_CM = 20.0
FLOOR_NORMAL_CM = 8.0
FLOOR_DROP_THRESHOLD_CM = 18.0

# Speed targets
CRUISE_RPM = 90.0
CAUTION_RPM = 55.0
RECOVERY_RPM = 40.0
ESCAPE_RPM = 45.0

# Steering limits
CAMERA_BIAS_MAX_DEG = 5.0
SOFT_AVOID_DEG = 15.0
ESCAPE_STEERING_DEG = 30.0

# Recovery behavior
RECOVERY_DISTANCE_CM = 8.0
BRAKE_DELAY_SECONDS = 0.25

# Communication
SERIAL_PORT = "/dev/ttyACM0"
SERIAL_BAUDRATE = 115200
COMMAND_RATE_HZ = 20
TELEMETRY_RATE_HZ = 10